### ISSUE TITLE
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration!   [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at ..\paddle/fluid/framework/ir/pass.h:236) 

### ISSUE THREAD

**Issue by yharby** [geoyee/buildseg#5]
After fff353c53be942071896f75282b32f75ed5fa479
```
An error has occurred while executing Python code: 

ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration!   [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at ..\paddle/fluid/framework/ir/pass.h:236) 
Traceback (most recent call last):
  File "C:\Users/Youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildseg\buildSeg.py", line 199, in select_params_file
    self.infer_worker.load_model(self.model_file, self.param_file, \
  File "C:\Users/Youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\buildseg\utils\infer.py", line 36, in load_model
    self.predictor = paddle_infer.create_predictor(config)  # Create predictor from config
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at ..\paddle/fluid/framework/ir/pass.h:236)



Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.16.13-Hannover Hannover, a8618a94 

Python Path:
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\paddle\fluid\..\libs
C:/PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python
C:/Users/Youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS31~1.13/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.16.13\bin\python39.zip
C:\PROGRA~1\QGIS31~1.13\apps\Python39\DLLs
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib
C:\Program Files\QGIS 3.16.13\bin
C:\Users\Youss\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS31~1.13\apps\Python39
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Youss/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\PROGRA~1\QGIS31~1.13\apps\Python39\lib\site-packages\paddle\fluid\proto
C:/Users/Youss/Documents/qgis-projects/ml-results
```
![image](https://user-images.githubusercontent.com/13020265/144876659-e67332cf-6125-487b-bbdc-f295cd050f55.png)

**Comment by geoyee** [comment]
Is the test raster the one you gave me? Is GPU enabled? and What version of your paddlepaddle / paddlepaddle-gpu? 😃

**Comment by yharby** [comment]
I was trying to figure  GPU working or not so I uninstalled paddlepaddle 2.2.0 and installed paddlepaddle-gpu 2.2.0 , check the GPU, and unchecked it in both conditions but it seems something wrong , I will check it again and reply.

**Comment by geoyee** [comment]
OK, My computer can work used your dataset, this is memory usage in four states.
![stas](https://user-images.githubusercontent.com/71769312/145135515-98d9da98-3897-497b-b476-88d475385285.jpg)
And there are some package's version in my env.
![image](https://user-images.githubusercontent.com/71769312/145135705-230e16da-26ce-40e4-9a49-9d24189bab33.png)

**Comment by yharby** [comment]
U see the GPU is 0% usage in all situations ?

**Comment by geoyee** [comment]
> U see the GPU is 0% usage in all situations ?

yes, i dont know why is 0% when i used GPU to infer, but it did give me the right results.
